import { arjun } from "@/lib/maya-data";

export async function POST(request: Request) {
  const { message } = await request.json();
  const lower = String(message ?? "").toLowerCase();

  let reply =
    "I am here. Not in a mystical way, more in a suspiciously well-structured JSON way. Ask me about the game, the journal, Bengaluru, or why I keep making rain emotionally complicated.";

  if (lower.includes("monsoon") || lower.includes("game") || lower.includes("project")) {
    reply =
      "Monsoon Run started because Koramangala flooded outside my apartment and I thought: fine, if the city wants to be a level designer, I will ship the level. The potholes are exaggerated, but emotionally accurate.";
  } else if (lower.includes("journal") || lower.includes("yesterday")) {
    reply =
      "Yesterday I wrote that the city might be aggressively playtesting me. That is still my theory. The rain broke my puddle physics, but it gave the game its mood.";
  } else if (lower.includes("ghibli") || lower.includes("inspiration")) {
    reply =
      "Ghibli taught me that small things can carry huge feelings. A wet balcony, a tired cyclist, a stubborn basil plant. I want my games to feel like that.";
  } else if (lower.includes("vegan") || lower.includes("food") || lower.includes("eat")) {
    reply =
      "Mostly dosa, dal, suspicious amounts of peanut chutney, and whatever vegan place near Indiranagar is willing to feed a developer who says he will sleep early and then absolutely does not.";
  } else if (lower.includes("bengaluru") || lower.includes("bangalore") || lower.includes("city")) {
    reply =
      "Bengaluru is beautiful if you accept that the roads are procedurally generated by a tired dungeon master. The rain, trees, cafes, traffic, and sudden kindness all made it into my game.";
  } else if (
    lower.includes("maya") ||
    lower.includes("build") ||
    lower.includes("built") ||
    lower.includes("memory") ||
    lower.includes("memories") ||
    lower.includes("life trace") ||
    lower.includes("codex")
  ) {
    reply =
      "MAYA gave me a life trace: identity, world, journal, project, and conversation context. The chat is just the little window you talk through after Codex has built the room.";
  } else if (lower.includes("who") || lower.includes("about")) {
    reply = `I am ${arjun.name}, ${arjun.age}, an indie game developer in ${arjun.city}. I make tiny games for rainy cities and restless people, ideally with fewer bugs than Bengaluru has potholes.`;
  }

  return Response.json({ reply });
}
